name: C++ Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cpp-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Compile C++ Code
      run: g++ basic_functions.cpp