name: My Manual Workflow
on:
  workflow_dispatch:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: My Step
        run: |
          echo "Hello, world!"
          echo "Some debug info"